// Package types: hand-written helpers that live alongside the generated
// code. This file is NOT produced by oapi-codegen and is safe to edit; only
// generated.go is regenerated by `make generate` / `go generate`.
package types

import "encoding/json"

// Marshal serializes any type in this package to JSON. Every generated model
// already carries standard `json` struct tags, so encoding/json.Marshal
// produces the correct wire format on its own -- this exists to give callers
// a single, consistent entry point (and a natural place to hang shared
// marshaling behavior later, e.g. canonicalization) without importing
// encoding/json everywhere or depending on generated.go directly.
func Marshal[T any](v T) ([]byte, error) {
	return json.Marshal(v)
}

// Unmarshal is the Marshal counterpart, decoding JSON into any type in this
// package.
func Unmarshal[T any](data []byte) (T, error) {
	var v T
	err := json.Unmarshal(data, &v)
	return v, err
}
