// Package types: hand-written helpers that live alongside the generated
// code. This file is NOT produced by oapi-codegen and is safe to edit; only
// generated.go is regenerated by `make generate` / `go generate`.
package types

// NewProblem builds a Problem for the given HTTP status, title, and detail
// message. It exists because Problem.Detail is a *string -- taking the
// address of a string literal isn't valid Go, so every call site would
// otherwise need its own throwaway local variable -- and because the
// int32(status) narrowing conversion needs exactly one lint suppression
// rather than one per call site.
func NewProblem(status int, title, detail string) Problem {
	return Problem{
		//nolint:gosec // status is always an http.Status* constant, well within int32 range
		Status: int32(status),
		Title:  title,
		Detail: &detail,
	}
}
